project:
  type: website
  output-dir: docs


website:
  title: "ğŸ‘°ğŸ’ğŸ¤µ"
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: location.qmd
        text: Unterkunft
      - href: weekend.qmd
        text: Wochenende
      - href: wedding.qmd
        text: Hochzeit
      - href: eat_and_drink.qmd
        text: Essen und Trinken
      - href: anreise.qmd
        text: Anreise
      - href: the_ring.qmd     
        text: Ringe
      - href: about.qmd 
        text: About
  body-header: | 
    ![](/img/MandlwandTest.jpg)

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true
